sudo: false
language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js: '8'
script: npm run validate
branches:
  only: master
after_success:
  - firebase deploy --only hosting --project faster-mta --token $FIREBASE_TOKEN
