sudo: false
language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js: '8'
script: npm run validate
branches:
  only: master
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: YhtU1ryBxdOI7tH3wFn7kGOrOdk3z4qNVzEiRDCrAZwtzSRaue5TeoGyWsS7FsON0slsymPx+kf4CG2TUelmJFv491u+M+HQdHuNIHCRnld7wSx/YCc+6AVcEWVOIwRVYtHGpo6fr+ZfLKaY0L4VjvJ8joNvlYj+m6qz/ayFaOgPw7881yk4SfnuESXkJlb7htu6rTRtHjBdgzFfvTS0lFr/zVhQtD/wbaYViwuOnwFdfpr43Hr4p1y7nmdDnUVHlKlTdNnyNFOFSsEvfYqBMk5U7aZnRYqm/uhbwiWxh3Tz3w6pl2JnbnGg6ITRgyKwgFaCuoSnwDFn/feRG+cPXC73GndGDLw4CNSGNwKlvtogx8G+fzLKYN6BDMZSQoI7PfLm0QO9OPuvNiuoWskW5U69R8+M1n4ppsIUxBjcd3xLBwApOtxmDJcx/MZhRO75oHMl/LZNS0tnPJscuBLEERNv7AU1rB7+qJzfLbLKyqB9/XQn/y9NyES7tzV6y/gXH1TVhcIHrUxTxHdXrt9E4M/m8HRUZLa5oPEq8/zVcawazlQMTJ/gfdibcsUDTIPsW9/5oecFlcJLcBWo9KzS9EwYSiioaN7cf5CGdp8KB6vVF7NT/Ki1/iXE0Gpm0KWsXutlvCQfJtdaOWxYOZP0nO/EksMAtFcu7qq47YD1LZI=