sudo: false
language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js: '8'
script: npm run validate
branches:
  only: master
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: "p2os8oxVNyUY4d3tZafwP2m9h6PMoN7a3ItcxvAVq4F+NFMDfG2lBrQRcS5+tsdZY1LKqCO387FeXfR1+fUusghas6ikzItTbyzopQEkvRo4aBQkmNIbiV3hggdGJOLu+FkhOny9UroZJwxZOpK93ESXMqBXVZwsmx/ZNrW7pymMr5T3o3jJ6fLsZZdO54Gh+RKjxEuPfpgxrBp0x9h/GVf6//1yFGVFlhMI88Rdf4RBOCCzGkz/lNtw66p3OBblKjaQtxcf+X+7lNWF/eHBq0b3fDpZ0DP6tmj5TK5tXx/pHVHlAyaswpljYQ9cHUM0Ti0ZCehKboTF//e4mVT129pHFWqsPHknDChzeEIVj7HMAGgkEFEUoQoAD2OxMOpRtpUFPCJz07v6x1R/hdXwr0FH31HwWptzgbxg8/XqON1fRC7CUB29VdUMDuME5GqktIgeFI2Bif4cKxMiQ+7NPsFYQ+qOcfIPbP62S/C7q4xStYVqCMVSjIjPCNBc99KE5k0N8w8CfBaAs3CdtELoMnYugA+EfWa/gGim4dg/p1uM0PKqoS0svSGCQ7sxJq0lz41CKnCbJhWddPHiOMBuvKDazTJrW9zIBvODk6KZRXWZSmb01Jwx7H5iMx4qPoD4KM4tKgjTCS2MGPjCeG2XrxFCNMJa0PvjP3Nm465p/bg="